### ISSUE TITLE
Use fixed-length method selector

### ISSUE THREAD

**Issue by lrettig** [athenavm/athena#113]
In #112 we added message name to the execution message. Rather than using variable-length strings, let's move to a fixed-length selector. EVM uses four bytes, see: https://solidity-by-example.org/function-selector/.

For simplicity we can use something like a four byte hash of the method name.

**Comment by poszu** [comment]
A 4B selector seems excessive. We hardly need to support 4G methods in a program. How about we use one byte only and implement support for calculating the id for each `#[callable]` method automatically or with optional manual override like `#[callable(id=2)]`? The automatic could just number methods top-down 1,2,3,4.... We could reserve `0` for the "main" (programs without methods). Wdyt?

**Comment by lrettig** [comment]
I think a hash makes more sense. The point here is that the calculation is deterministic with a hash -- all you need to know is the method name and/or its signature. Any dumb web wallet client could thus construct a transaction without knowing the logic happening inside our Rust macros.

**Comment by poszu** [comment]
Well, with `#[callable(id=2)]` it is deterministic, easy to use by clients, smaller, and free of hash collisions.  With the hash approach, the client developer would need to open the source code, find the function name and hash it. In both cases, most likely, these identifiers would just be put in program's documentation anyway :shrug:.

**Comment by lrettig** [comment]
I think the other issue with integer ids is that they might change over time. Assuming the macro assigns them in order, what if you add a new function between two existing functions? Doing so should not break existing code.

Either way, the client/application developer does need metadata (not necessarily the on-chain program source code), like the contract ABI for eth.
