### ISSUE TITLE
Return u64 from `get_balance` in the athcon FFI

### ISSUE THREAD

**Issue by poszu** [athenavm/athena#140]
Currently, the `get_balance()` function returns a `athcon_uint256be`:
https://github.com/athenavm/athena/blob/96b9afa3f8e08e24506b5466218842354eb40afb/ffi/athcon/include/athcon/athcon.h#L549-L559

Which is supposed to be a 256bit big-endian integer encoded in a byte array:
https://github.com/athenavm/athena/blob/96b9afa3f8e08e24506b5466218842354eb40afb/ffi/athcon/include/athcon/athcon.h#L43-L46

There are two problems with it:
- the athena balance is `u64` so its inefficient to pass it as 256bits
- it's supposed to be big-endian (according to the type description) but we put the value as little-endian there

IMHO, we should change the C API to return a uint64_t instead to avoid confusion, make it efficient and simplify the code.

**Comment by lrettig** [comment]
Good catch. We use u64 in go-spacemesh so we should do the same in Athena. In any case it's more general than uint256.
