### ISSUE TITLE
Blake3 output not deterministic in guest

### ISSUE THREAD

**Issue by lrettig** [athenavm/athena#149]
Blake3 is exhibiting strange, non-deterministic behavior when running in the guest. Here's a simple test:

https://github.com/athenavm/athena/blob/32ea2b529ecf9aca8d503cb7f8ef175550fa9bdb/tests/hasher/src/main.rs#L11-L34

It produces this output:

```
> (cd tests/hasher && cargo athena execute)

[athena]      Finished `release` profile [optimized] target(s) in 0.04s
Root package name: "hasher-test"
Target "hasher-test" artifact path: "hasher-test"
Creating output dir "athena/athena/tests/hasher/elf"
Copying original artifact "athena/athena/tests/hasher/target/elf-compilation/riscv32em-athena-zkvm-elf/release/hasher-test" to final path: "athena/athena/tests/hasher/elf/hasher-test"
2024-10-12T19:27:42.951223Z  INFO Initializing    
2024-10-12T19:27:42.951235Z  INFO loading memory image
2024-10-12T19:27:42.951569Z  INFO starting execution
2024-10-12T19:27:42.951574Z  INFO clk = 0 global_clk = 0 pc = 0x201d9c    
stdout: value: athexp_test2; as_bytes: 6174686578705f7465737432; hash: bd62654f3ffc34f6214542df5cd19b9e73cd017f837a01f67efc9106e3be6e30
stdout: value: athexp_test2; as_bytes: 6174686578705f7465737432; hash: e0609f2e9cd03f757397afa94575d8a40fa2d5e2c88afe164522e492496bb2bd
stdout: value: athexp_test2; as_bytes: 6174686578705f7465737432; hash: b7119b933731767cbc785d3a35c142853b4e4feab32f14f2a5043c52eee007a8
2024-10-12T19:27:42.953248Z  INFO Execution finished    
2024-10-12T19:27:42.953251Z  INFO finished execution clk = 86412 global_clk = 21603 pc = 0x0
    Finished executing in 0.00s
    Finished received 0 bytes output
```

**Comment by lrettig** [comment]
@poszu suggested that it's likely a memory issue and I agree. I looked for any memory issues that have been fixed in the upstream SP1 and didn't find any obvious ones, but I also noticed that the SP1 core runtime was rewritten in https://github.com/succinctlabs/sp1/pull/1036.

I narrowed it down to an issue with [this data structure](https://github.com/BLAKE3-team/BLAKE3/blob/aa3e8ec32a389461babde3789d6ac50ee3c38662/src/lib.rs#L469-L477); the second time the hash function is called, the `buf` isn't correctly [initialized to zeroes](https://github.com/BLAKE3-team/BLAKE3/blob/aa3e8ec32a389461babde3789d6ac50ee3c38662/src/lib.rs#L484), which causes problems in [this method](https://github.com/BLAKE3-team/BLAKE3/blob/aa3e8ec32a389461babde3789d6ac50ee3c38662/src/lib.rs#L496-L502).

**Comment by poszu** [comment]
I created a smaller test to reproduce it: https://github.com/athenavm/athena/blob/debug/corrupted-stack-init/tests/hasher/src/main.rs

After attaching GDB, I can see that parts of the `buf` array are not properly initialized to zeros the second time:

```
Breakpoint 1, hasher_test::main () at tests/hasher/src/main.rs:13
13	    println!("{buf:?}");

**Comment by poszu** [comment]
@lrettig The issue is most likely in memset-rv32e.s, although I have not yet found the bug. I replaced its implementation with a chat-gpt generated one and it works both in my simple test and with the blake3 hasher test of yours: https://github.com/athenavm/athena/blob/debug/corrupted-stack-init/vm/entrypoint/src/memset-rv32e.s
