### ISSUE TITLE
Make script in newly-created program immediately runnable

### ISSUE THREAD

**Issue by lrettig** [athenavm/athena#50]
There's a hardcoded line in the script created with `cargo athena new` that's troublesome:

https://github.com/athenavm/athena/blob/19f2ff6f7a4bae22f4c84f98d03271b3ec418443/cli/src/assets/script/main.rs#L7

This fails because the executable name doesn't match the program name, e.g.:

```
> cargo new foo
> cd foo/script
> cargo build
warning: foo-script@0.1.0: foo-program built at 2024-07-21 19:02:05
error: couldn't read `src/../../program/elf/fibonacci-program`: No such file or directory (os error 2)
 --> src/main.rs:7:20
  |
7 | const ELF: &[u8] = include_bytes!("../../program/elf/fibonacci-program");
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

The following warnings were emitted during compilation:

warning: foo-script@0.1.0: foo-program built at 2024-07-21 19:02:05

error: could not compile `foo-script` (bin "foo-script") due to 1 previous error
```

One possible fix is to fix `cargo athena new` to update this line. Another possible fix is to not make the ELF file name depend on the project name.

**Comment by poszu** [comment]
Closing as the athena/cli/src/assets/script/main.rs was already removed.
